#include "Exception.h"

//#define DEBUG

namespace planning {

Exception::Exception()
{
	#ifdef DEBUG
		cout << "[Exception] Appel constructeur par dÃ©faut" << endl;
	#endif

	setMessage("Pas de message");
}

//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////

Exception::Exception(const Exception& e)
{
	#ifdef DEBUG
		cout << "[Exception] Appel constructeur de copie" << endl;
	#endif

	setMessage(e.getMessage());
}

//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////

Exception::Exception(const string m)
{
	#ifdef DEBUG
		cout << "[Exception] Appel constructeur d'initialisation" << endl;
	#endif

	setMessage(m);
}

//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////

Exception::~Exception()
{
	#ifdef DEBUG
		cout << "[Exception] Appel destructeur" << endl;
	#endif
}

//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
	
void Exception::setMessage(string m)
{
	message = m;
}

//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////

string Exception::getMessage() const
{
	return message;
}

}